### ISSUE TITLE
Cant upload file "Bucket Pub" ... is not a valid json

### ISSUE THREAD

**Issue by MohamedIrfanAM** [edgestorejs/edgestore#14]
When edgestore.publicFiles.upload() is called these errors are shows and file is not uploaded
![image](https://github.com/edgestorejs/edgestore/assets/64521698/00df3419-8dd6-4364-b7ef-cd1214d1fd15)
![image](https://github.com/edgestorejs/edgestore/assets/64521698/8907da4c-a2be-4b2c-a65a-04575e55cc2a)

**Comment by perfectbase** [comment]
Hi @MohamedIrfanAM,
Sorry that the errors are not easy to understand... I'll work on improving that.

That said. I'll need more information about your code to be able to debug it.
If you can share a minimal reproducible repo so that I can take a look, that would be nice.

You can also try to run the example app in your machine.
Here are the steps to run the example app:
- clone the repo: `git clone https://github.com/edgestorejs/edgestore.git`
- cd into the example app: `cd examples/next-basic`
- run `npm install`
- add your environment variables to `examples/next-basic/.env.local`
- run `npm run dev`
- access the page at http://localhost:3000

If this works, you can try to find the difference to your project and try to fix it.

Let me know if this helps.
