### ISSUE TITLE
Module not found: Can't resolve '@edgestore/shared'  after yarn upgrade

### ISSUE THREAD

**Issue by eunoya-dev** [edgestorejs/edgestore#30]
I got this error after I ran yarn upgrade, before that there wasn't any error, why did this happen?

![Screenshot 2023-12-25 215339](https://github.com/edgestorejs/edgestore/assets/140743646/50edf7cd-bce7-4045-8028-45136211d3eb)

this is file on lib/edgestore.ts
![Screenshot 2023-12-25 215615](https://github.com/edgestorejs/edgestore/assets/140743646/27e7e2ae-864d-4b04-beb1-c95e345cf791)

**Comment by VincentWijaya** [comment]
Same here

**Comment by perfectbase** [comment]
@eunoya-dev @VincentWijaya 
Thank you for reporting this. I was able to replicate the problem here.
It works with `npm` and `pnpm`, but not for `yarn`.
it seems that `yarn` is not installing the `shared` dependency properly.
as a workaround, you can add it directly to the `package.json`

```
"@edgestore/shared": "0.1.5",
```

I'll try to fix this dependency issue in the next version.

**Comment by eunoya-dev** [comment]
> @eunoya-dev @VincentWijaya Thank you for reporting this. I was able to replicate the problem here. It works with `npm` and `pnpm`, but not for `yarn`. it seems that `yarn` is not installing the `shared` dependency properly. as a workaround, you can add it directly to the `package.json`
> 
> ```
> "@edgestore/shared": "0.1.5",
> ```
> 
> I'll try to fix this dependency issue in the next version.

Thanks, it works 😍

**Comment by perfectbase** [comment]
The problem should be fixed now on version `0.1.6`.
