### ISSUE TITLE
Missing edgestore-ctx cookie "UNAUTHORIZED"

### ISSUE THREAD

**Issue by copyPasteNinja** [edgestorejs/edgestore#46]
I have EdgeStore setup with AWS provider in my NextJS app version 14. I haven't come across this issue before until today. Locally it seems to work fine. I double checked the variables and credentials are provided. Here is the error I'm facing: 

```
{message: "Missing edgestore-ctx cookie", code: "UNAUTHORIZED" } code: "UNAUTHORIZED" message: "Missing edgestore-ctx cookie"
```

I enabled the debug mode, I see the edgestore-ctx being created after successful initialization: 
```
DEBUG	[EdgeStoreDebug] Finished [init] {
  ctx: {},
  newCookies: [
    'edgestore-ctx=*********************.D7cYW8E01jnwYBPD.PXciUa55XMu8Dv7yOfCujvL5TQMtaNpgYqMcl51a84ftOUHeFhGw_W4Yvag0M7YWl1wDXAl-HdUkNJoKjL_csVH8bxcb04fCTgCJ*******************; Max-Age=2592000; Path=/'
  ],
  token: undefined,
  baseUrl: 'https://s3-bucket-name.us-west-1.amazonaws.com'
}
```

I could use some assistance, thanks.

**Comment by KBerkeYilmaz** [comment]
Same issue here, issue started after I've add multifile component to my app. I use NextJs 14 // App Router. Now single upload won't work too. 

Production works fine but I haven't push the latest update. 

[EdgeStoreDebug] Creating Edge Store Next handler (app adapter)
[EdgeStoreDebug] Creating Edge Store Next handler (app adapter)
[EdgeStoreDebug] Running [init] { ctx: {} }
[EdgeStoreError] TypeError: fetch failed
  cause: Error [ERR_SOCKET_CONNECTION_TIMEOUT]: Socket connection timeout
      at new NodeError (node:internal/errors:399:5)
      at internalConnectMultiple (node:net:1099:20)
      at Timeout.internalConnectMultipleTimeout (node:net:1638:3)
      at listOnTimeout (node:internal/timers:575:11)
      at process.processTimers (node:internal/timers:514:7) {
    code: 'ERR_SOCKET_CONNECTION_TIMEOUT'

**Comment by perfectbase** [comment]
Hi @KBerkeYilmaz 
This issue was being handled [here](https://discord.com/channels/1060144459431559208/1166757709878677585/1221146948808216648).

I couldn't replicate the problem here.
Are you also using the AWS Provider?

You could try to run the [next-basic-aws](https://github.com/edgestorejs/edgestore/tree/main/examples/next-basic-aws) example to see if you find the problem with your app.

You can find more information here:
https://edgestore.dev/docs/troubleshooting

If you try it, but still can't figure out the problem with your app, you can share a minimal reproducible repo so I can take a look. If possible, you should base the repo from the `next-basic-aws` example without doing big changes to it.

I hope it helps!

**Comment by KBerkeYilmaz** [comment]
Hi @perfectbase,

Thank you for your response.

I deployed it on vercel. But after focusing the 500 error itself and finding similar issues on stackoverflow with different services I managed to isolate it to my local network. Took a chance and pushed it to prod, everything works fine. 

For future issues, maybe ctx verification might allow a longer response time in development?
