### ISSUE TITLE
CORS policy: No 'Access-Control-Allow-Origin' 

### ISSUE THREAD

**Issue by ivoneijr** [edgestorejs/edgestore#8]
Hey, hello.

I'm using edgestore in my nextjs app hosted in vercel, everything works fine in localhost, but when I try to upload files in my vercel app I get a cors error

```
Access to fetch at 'https://files.edgestore.dev/.../publicFiles/_public/uuid.pdf' from origin 'https://myhost.vercel.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
1866d874-9d824f0eb67088a0.js:22 
        
        
GET https://files.edgestore.dev/.../publicFiles/_public/uuid.pdf net::ERR_FAILED 200 (OK)
```

I tried to bypass the cors config in `vercel.json` but no success.

Any ideas ?

**Comment by perfectbase** [comment]
@ivoneijr Thank you for creating the issue!
I'll also paste here the discord answer as it may be useful for others:

I think I know what the problem is.
Your app is using the react-pdf package, which is trying to download the pdf from the frontend code, which is in another domain, so you get a CORS error.

I think that for your use-case you can try to use the proxy-file api.
there is an api under the api/edgestore/proxy-file that can get the file from other domains by proxying it through your api. You just need to pass in a url parameter with the encoded url for the file.

something like this:
```ts
function getProxyUrl(url: string) {
  const proxyUrl = new URL("https://my.site/api/edgestore/proxy-file");
  proxyUrl.search = new URLSearchParams({
    url,
  }).toString();
  return proxyUrl.toString();
}
// The url will look something like this:
// https://my.site/api/edgestore/proxy-file?url=https%3A%2F%2Ffiles.edgestore.dev%2Ftest
```

I didn't test this.. so if you have any problems, let me know.
if that works, I'll probably make it into an util function to make it easier to handle.

**Comment by perfectbase** [comment]
@ivoneijr I decided to add the CORS headers to the response of all files. That means that you should be able to get rid of the proxy workaround and use the react-pdf with the original url directly.
